name = "Create Fabulously [Fabric]"
author = "Lucas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e3e7a37153ad3739aacaf48f930b99a4916403ab2f680ad3c5d296bd233825b"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
