name = "Create Fabulously [Fabric]"
author = "Lucas"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a22626ef91988cb037aa44fa6499e5121a3c57ba4d9f1fb91a9dddec53127a3"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
