name = "Create Fabulously [Fabric]"
author = "Lucas"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "090717cb3f19043140a4647cdb236949db14e939b217e11110b6838ee640eeef"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
